openapi: 3.0.3
info:
  title: simple oauth API
  description: |-
    설명
servers:
  - url: http://localhost:3000
tags:
  - name: authorization
    description: 클라이언트에 인증을 처리해주는 서비스
    externalDocs:
      description: Find out more
      url: http://localhost:3000/authorization
paths:
  /code:
    post:
      tags:
        - authorization
      summary: authorization_code 발급
      description: access token을 얻기 위한 코드를 발급합니다
      operationId: getAuthorizeCode
      requestBody:
        description: 클라이언트 정보가 있습니다
        content:
          application/json:
            schema:
              type: object
              properties:
                clientId:
                  type: integer
                  example: 1
                grantType:
                  type: string
                  example: 'authorization_code'
                redirectUrl:
                  type: string
                  example: 'localhost/receivecode'
                codeChallenge:
                  type: string
                  example: 'asd2123dad3r3rkr'
                codeChallengeMethod:
                  type: string
                  example: 'sha256'
        required: true
      responses:
        '201':
          description: Created OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: 'eff414be-1567-44a6-bfe9-fad2742b58fd'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /token:
    post:
      tags:
        - authorization
      summary: access token
      description: 발급 받은 코드로 새로운 access token을 받습니다
      operationId: getAccessToken
      requestBody:
        description:
        content:
          application/json:
            schema:
              type: object
              properties:
                clientId:
                  type: integer
                  example: 1
                grantType:
                  type: string
                  example: 'authorization_code'
                redirectUrl:
                  type: string
                  example: 'localhost:3000'
                codeVerifier:
                  type: string
                  example: 'MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTE'
                code:
                  type: string
                  example: '04ade727-bc14-4c5c-92c0-2bb2151e7cb5'
        required: true
      responses:
        '201':
          description: Created OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiLrsJzquIkgRE5TIiwiYXVkIjoi67Cc6riJ7J6QIiwiY2xpZW50SWQiOjEsImlhdCI6MTY2NDI1ODAxMCwiZXhwIjoxNjY0MjYxNjEwfQ.D6vGf_NEkdTavUkMRIp66GnZsQfQd7LUYZvL1W_lTf0'
                  refreshToken:
                    type: string
                    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiLrsJzquIkgRE5TIiwiYXVkIjoi67Cc6riJ7J6QIiwiY2xpZW50SWQiOjEsImlhdCI6MTY2NDI1ODAxMCwiZXhwIjoxNjY0ODYyODEwfQ.4mIChQtjB_JxZYp2Lix8LC7L1tf3xtO7gaNg6ht6Ppk'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /refresh:
    post:
      tags:
        - authorization
      summary: refresh token
      description: refresh token으로 access token를 재발급합니다
      operationId: refreshAccessToken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
                  example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiLrsJzquIkgRE5TIiwiYXVkIjoi67Cc6riJ7J6QIiwiY2xpZW50SWQiOjEsImlhdCI6MTY2NDI1ODAxMCwiZXhwIjoxNjY0ODYyODEwfQ.4mIChQtjB_JxZYp2Lix8LC7L1tf3xtO7gaNg6ht6Ppk'
        required: true
      responses:
        '200':
          description: Created Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiLrsJzquIkgRE5TIiwiYXVkIjoi67Cc6riJ7J6QIiwiY2xpZW50SWQiOjEsImlhdCI6MTY2NDI1ODAxMCwiZXhwIjoxNjY0MjYxNjEwfQ.D6vGf_NEkdTavUkMRIp66GnZsQfQd7LUYZvL1W_lTf0'
                  refreshToken:
                    type: string
                    example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiLrsJzquIkgRE5TIiwiYXVkIjoi67Cc6riJ7J6QIiwiY2xpZW50SWQiOjEsImlhdCI6MTY2NDI1ODAxMCwiZXhwIjoxNjY0ODYyODEwfQ.4mIChQtjB_JxZYp2Lix8LC7L1tf3xtO7gaNg6ht6Ppk'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
